Чувашов Владислав Максимович

Т120-101М-20

Лабораторная работа по Pandas № 2

In [2]:
import numpy as np
import pandas as pd

1   Получить от объекта Series показатели описательной статистики

In [6]:
pd.Series(np.arange(5)).describe()

count    5.000000
mean     2.000000
std      1.581139
min      0.000000
25%      1.000000
50%      2.000000
75%      3.000000
max      4.000000
dtype: float64

2 Узнать частоту уникальных элементов объекта Series (гистограмма)

In [38]:
Z=pd.Series(np.random.randint(1,5,size=13)).value_counts()
Z

4    5
2    4
3    3
1    1
dtype: int64

3 Заменить все элементы объекта Series на "Other", кроме двух наиболее часто встречающихся

In [39]:
Z[~Z.isin(Z.value_counts().index[:2])] = 'Other'
Z

4        5
2        4
3    Other
1    Other
dtype: object

4 Создать объект Series в индексах дата каждый день 2019 года, в значениях случайное значение

In [44]:
dti = pd.date_range(start='2019-01-01', end='2019-12-31', freq='B') 
Z = pd.Series(np.random.rand(len(dti)), index=dti)

5 Найти сумму всех вторников

In [48]:
X = Z[Z.index.weekday == 2].sum()
print('Сумма всех вторников равна', X)

Сумма всех вторников равна 26.796148786241048

6 Для каждого месяца найти среднее значение

In [61]:
Y = Z.resample('M').mean()
print('Средние значения по месяцам: \n ',Y)

Средние значения по месяцам:
  2019-01-31    0.574906
2019-02-28    0.481011
2019-03-31    0.503789
2019-04-30    0.647270
2019-05-31    0.407376
2019-06-30    0.426195
2019-07-31    0.533100
2019-08-31    0.438199
2019-09-30    0.397889
2019-10-31    0.549877
2019-11-30    0.452776
2019-12-31    0.445859
Freq: M, dtype: float64

7 Преобразовать объект Series в DataFrame заданной формы (shape)

In [79]:
Z = pd.Series(np.random.randint(low=1, high=10, size=[20]))
print (Z)
shape = (4, 5)
pd.DataFrame(Z.values.reshape(shape))

0     2
1     2
2     2
3     4
4     6
5     5
6     2
7     2
8     9
9     4
10    6
11    9
12    3
13    1
14    7
15    4
16    8
17    2
18    1
19    2
dtype: int64

   0  1  2  3  4
0  2  2  2  4  6
1  5  2  2  9  4
2  6  9  3  1  7
3  4  8  2  1  2

8 Найти индексы объекта Series кратные 3

In [77]:
Z = pd.Series(np.random.randint(low=1, high=10, size=[10]))
print(Z) 
Z[Z % 3 == 0].index

0    6
1    3
2    1
3    3
4    5
5    7
6    7
7    7
8    3
9    6
dtype: int64

Int64Index([0, 1, 3, 8, 9], dtype='int64')

9  Получить данные по индексам объекта Series

In [81]:
X = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
Y = [0, 4, 8, 14, 20, 10]
Z=X[Y]
print(Z)

0     a
4     e
8     i
14    o
20    u
10    k
dtype: object

10 Объединить два объекта Series вертикально и горизонтально

In [83]:
X = pd.Series(range(5))
Y = pd.Series(list('abcde'))
ver=X.append(Y)
print(ver)
gor=pd.concat([X,Y],axis=1)
print(gor)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

11 Получить индексы объекта Series A, данные которых содержатся в объекте Series B

In [89]:
A = pd.Series([1, 2, 3, 4, 5, 6])
B = pd.Series([4, 5, 6, 7, 8, 9])
A[A.isin(B)].index

Int64Index([3, 4, 5], dtype='int64')

12 Получить объект Series B, который содержит элементы без повторений объекта A

In [91]:
A = pd.Series(np.random.randint(low=1, high=10, size=[10]))
print (A)
B=pd.Series(A.unique())
print (B)

0    6
1    9
2    4
3    2
4    4
5    7
6    4
7    6
8    3
9    9
dtype: int64
0    6
1    9
2    4
3    2
4    7
5    3
dtype: int64

13 Преобразовать каждый символ объекта Series в верхний регистр

In [114]:
X = pd.Series(['i', 'love', 'python', 'very', 'much'])
Y=pd.Series(i.title()for i in X)
print(Y)

0         I
1      Love
2    Python
3      Very
4      Much
dtype: object

14 Преобразовать данные Series в строку

In [116]:
Z = pd.Series(str(i) for i in Y)
print(Z)

0         I
1      Love
2    Python
3      Very
4      Much
dtype: object

15 Рассчитать количество символов в объекте Series

In [117]:
Y = np.asarray([len(i) for i in X])
print(Y)

[1 4 6 4 4]

16 Преобразовать в строковый тип

In [118]:
Z = pd.Series(str(i) for i in Y)
print(Z)

0    1
1    4
2    6
3    4
4    4
dtype: object

17 Найти разность между объектом Series и смещением объекта Series на n

In [120]:
n = 1
 
X = pd.Series([1, 10, 13, 15, 20, 100, 1000])
 
Y = X.diff(periods=n)
 
print(Y)

0      NaN
1      9.0
2      3.0
3      2.0
4      5.0
5     80.0
6    900.0
dtype: float64

18 Преобразовать разные форматы строк объекта Series в дату

In [122]:
X = pd.Series(['2017/01/01', '2015-02-02', '15 Jan 2019'])
Y = pd.Series(['14.02.2019', '22.01.2019', '01.03.2019'])
 
pd.to_datetime(Y, format='%d.%m.%Y'), pd.to_datetime(X)

(0   2019-02-14
 1   2019-01-22
 2   2019-03-01
 dtype: datetime64[ns],
 0   2017-01-01
 1   2015-02-02
 2   2019-01-15
 dtype: datetime64[ns])

19 Получить год, месяц, день, день недели, номер дня в году от объекта Series (string)

In [124]:
from dateutil.parser import parse
 
s = pd.Series(['01 Jan 2018', '02-02-2011', '20120303', '2013/04/04', '2018-12-31'])

20 Распарсить дату и время

In [125]:
s_ts = s.map(lambda x: parse(x, yearfirst=True))

21 Получить года

In [126]:
print(s_ts.dt.year)

0    2018
1    2011
2    2012
3    2013
4    2018
dtype: int64

22 Получить месяцы

In [127]:
print(s_ts.dt.month)

0     1
1     2
2     3
3     4
4    12
dtype: int64

23 Получить дни

In [128]:
print(s_ts.dt.day)

0     1
1     2
2     3
3     4
4    31
dtype: int64

24 Получить номер недели

In [129]:
print(s_ts.dt.weekofyear)

0     1
1     5
2     9
3    14
4     1
dtype: int64

25 Получить номер дня в году

In [130]:
print(s_ts.dt.dayofyear)

0      1
1     33
2     63
3     94
4    365
dtype: int64

26 Отобрать элементы объекта Series, которые содержат не менее двух гласных

In [135]:
from collections import Counter
 
s = pd.Series(['Vladislav', 'Baby', 'dont', 'hurt', 'me', 'Моя', 'Любимая', 'Песня'])
mask = s.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aieouyаеёиоуыэюя')]) >= 2)
ans = s[mask]
print(ans)

0    Vladislav
1         Baby
5          Моя
6      Любимая
7        Песня
dtype: object

27 Отобрать e-маилы из объекта Series (можно юзать регулярки)

In [137]:
import re
 
emails = pd.Series(['test text @test.com', 'test@mail.ru', 'test.2ru', 'test@pp'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
ans = emails[mask]
print(ans)

1    test@mail.ru
dtype: object

28 Получить среднее значение каждого уникального объекта Series s1 через "маску" другого объекта Series s2

In [140]:
n = 10
s1 = pd.Series(np.random.choice(['dog', 'cat', 'horse', 'bird'], n))
s2 = pd.Series(np.linspace(1,n,n))
ans = s2.groupby(s1).mean()
print(ans)

bird     6.666667
cat      6.000000
dog      4.500000
horse    4.000000
dtype: float64