Чувашов Владислав Максимович

Т120-101М-20

Лабораторная работа по Pandas № 4

In [1]:
import io
import sys
import requests
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

1 Прочитать файл CSV и перевести его в DataFrame
файл - 'https://github.com/Vladchuvashov/Domashka/blob/master/airports.csv'

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Vladchuvashov/Domashka/master/airports.csv')
df.head(11)

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447
5,ACK,Nantucket Memorial Airport,Nantucket,MA,USA,41.25305,-70.06018
6,ACT,Waco Regional Airport,Waco,TX,USA,31.61129,-97.23052
7,ACV,Arcata Airport,Arcata/Eureka,CA,USA,40.97812,-124.10862
8,ACY,Atlantic City International Airport,Atlantic City,NJ,USA,39.45758,-74.57717
9,ADK,Adak Airport,Adak,AK,USA,51.87796,-176.64603
10,ADQ,Kodiak Airport,Kodiak,AK,USA,57.74997,-152.49386

2 Прочитать файл CSV (определенные столбцы и определенное кол-во строк) и перевести его в DataFrame

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Vladchuvashov/Domashka/master/airports.csv',nrows=16, usecols=['AIRPORT', 'CITY', 'COUNTRY'],)
df

                                  AIRPORT           CITY COUNTRY
0     Lehigh Valley International Airport      Allentown     USA
1                Abilene Regional Airport        Abilene     USA
2       Albuquerque International Sunport    Albuquerque     USA
3               Aberdeen Regional Airport       Aberdeen     USA
4      Southwest Georgia Regional Airport         Albany     USA
5              Nantucket Memorial Airport      Nantucket     USA
6                   Waco Regional Airport           Waco     USA
7                          Arcata Airport  Arcata/Eureka     USA
8     Atlantic City International Airport  Atlantic City     USA
9                            Adak Airport           Adak     USA
10                         Kodiak Airport         Kodiak     USA
11       Alexandria International Airport     Alexandria     USA
12  Augusta Regional Airport (Bush Field)        Augusta     USA
13                    King Salmon Airport    King Salmon     USA
14           Albany International Airport         Albany     USA
15              Waterloo Regional Airport       Waterloo     USA

3 Прочитать файл CSV и перевести каждую 100-ую строку в DataFrame

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/Vladchuvashov/Domashka/master/airports.csv', chunksize=100)
df_each = pd.DataFrame()
for chunk in df:
    df_each = df_each.append(chunk.iloc[0,:])
df_each

,AIRPORT,CITY,COUNTRY,IATA_CODE,LATITUDE,LONGITUDE,STATE
0,Lehigh Valley International Airport,Allentown,USA,ABE,40.65236,-75.44040,PA
100,El Paso International Airport,El Paso,USA,ELP,31.80667,-106.37781,TX
200,Montgomery Regional Airport,Montgomery,USA,MGM,32.30064,-86.39398,AL
300,Syracuse Hancock International Airport,Syracuse,USA,SYR,43.11119,-76.10631,NY

4 Преобразовать индексы объекта Series в столбец DataFrame

In [5]:
s = pd.Series(list('абвгдеёжз'))

df = s.to_frame().reset_index()
df.columns=['номер', 'буква']
df

   номер буква
0      0     а
1      1     б
2      2     в
3      3     г
4      4     д
5      5     е
6      6     ё
7      7     ж
8      8     з

5 Посмотреть информацию объекта DataFrame

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/Vladchuvashov/Domashka/master/airports.csv')

1) Вывести формат каждого столбца

In [7]:
print('\n', 'Формат столбцов:')
print(df.dtypes)

 Формат столбцов:
IATA_CODE     object
AIRPORT       object
CITY          object
STATE         object
COUNTRY       object
LATITUDE     float64
LONGITUDE    float64
dtype: object

2) Вывести размерность DataFrame

In [8]:
print('\n', 'Размерность:')
print(df.shape)

 Размерность:
(322, 7)

3)  Вывести общую статистику

In [9]:
print('\n', 'Общая статистика:')
print(df.describe())

 Общая статистика:
         LATITUDE   LONGITUDE
count  319.000000  319.000000
mean    38.981244  -98.378964
std      8.616736   21.523492
min     13.483450 -176.646030
25%     33.652040 -110.839385
50%     39.297610  -93.403070
75%     43.154675  -82.722995
max     71.285450  -64.798560